-- RSVP(참석 의사) 테이블. PostgreSQL / H2(PostgreSQL 호환 모드) 공통.
CREATE TABLE rsvp (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50)  NOT NULL,
    contact      VARCHAR(20)  NOT NULL,
    side         VARCHAR(10)  NOT NULL,
    attendance   VARCHAR(20)  NOT NULL,
    adult_count  INTEGER,
    child_count  INTEGER,
    meal_option  VARCHAR(20),
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);

-- 연락처 기준 upsert 를 위한 유니크 제약
ALTER TABLE rsvp ADD CONSTRAINT uq_rsvp_contact UNIQUE (contact);

-- 보존 배치(만료 조회)용 인덱스
CREATE INDEX idx_rsvp_created_at ON rsvp (created_at);
